spring.application.name=veebipood
#server.port=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7bm5clm5p6s73f0j6r0-a.frankfurt-postgres.render.com/veebipood_database_8zmt
spring.datasource.username=veebipood_user
spring.datasource.password=kM5LzK0W0jllCSEm65P6MR0w0AOodyyq
